data:
  raw_path: data/raw/creditcard.csv
  processed_train: data/processed/train.csv
  processed_test: data/processed/test.csv
  test_size: 0.2
  random_state: 42

model:
  type: random_forest
  n_estimators: 200
  max_depth: 8
  class_weight: balanced
  n_jobs: -1

train:
  target_col: Class
  test_size: 0.2
  random_state: 42

mlflow:
  tracking_uri: "file:mlruns"
  experiment_name: "creditcard_fraud"

